javac -source 1.5 Share.java || pause
javac -source 1.5 PortfolioFund.java || pause
javac -source 1.5 Allocation.java || pause
javac -source 1.5 CategoryEntry.java || pause
javac -source 1.5 InvestorEntry.java || pause
javac -source 1.5 createTable.java || pause
javac -source 1.5 MutualFund.java || pause
javac -source 1.5 DBops.java || pause
javac -source 1.5 EraserThread.java || pause
javac -source 1.5 PasswordField.java || pause
javac -source 1.5 User.java || pause
javac -source 1.5 UserType.java || pause
javac -source 1.5 Customer.java || pause
javac -source 1.5 Admin.java || pause
javac -source 1.5 MutualFuture.java || pause